name: proj_cicd_test
description: to test the cicd process
version: v1
author: sharad.ghallal@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projcicdtest
  parentArtefactID: sharadghallalcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-07-31 13:12:28'
pipelines:
  pipelines/pl_cicd_test01:
    name: pl_cicd_test01
    description: to test the cicd process
    author: sharad.ghallal@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-31 13:15:01'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-31 13:12:28'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-07-31T13:12:28.531726Z'
  name: plibMaven
  version: 8.0.29
  id: '526226808'
  createdAt: '2024-07-31T13:12:28.531726Z'
  type: plibMaven
- modifiedAt: '2024-07-31T13:12:28.531726Z'
  name: plibPypi
  version: 1.9.9
  id: '738975966'
  createdAt: '2024-07-31T13:12:28.531726Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-31 13:11:46'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-31 13:11:46'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
