name: proj_cicd_test
description: to test the cicd process
version: v2
author: sharad.ghallal@cloudaeon.net
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: projcicdtest
  parentArtefactID: sharadghallalcloudaeonnetteam
  buildSystem: wheel
  author: null
  createdAt: '2024-07-31 13:12:28'
pipelines:
  pipelines/pl_cicd_test01:
    name: pl_cicd_test01
    description: to test the cicd process
    author: sharad.ghallal@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-07-31 13:15:01'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/pl_cicd_test02:
    name: pl_cicd_test02
    description: to test the dataset copy into cicd process
    author: sharad.ghallal@cloudaeon.net
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-08-01 08:21:21'
    datasets:
      inputs:
      - datasets/ds_src_01
      outputs:
      - datasets/ds_tgt_01
    subgraphs: []
    dependencies: {}
datasets:
  datasets/ds_src_01:
    name: ds_src_01
    description: ''
    author: sharad.ghallal@cloudaeon.net
    createdAt: '2024-08-01 08:21:55'
    mode: batch
    physicalDatasets:
      Job_test:
        fabricId: 13085
        datasetType: Database
        description: ''
        author: sharad.ghallal@cloudaeon.net
        createdAt: '2024-08-01 08:21:55'
  datasets/ds_tgt_01:
    name: ds_tgt_01
    description: ''
    author: sharad.ghallal@cloudaeon.net
    createdAt: '2024-08-01 08:22:36'
    mode: batch
    physicalDatasets:
      Job_test:
        fabricId: 13085
        datasetType: Database
        description: ''
        author: sharad.ghallal@cloudaeon.net
        createdAt: '2024-08-01 08:22:36'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-07-31 13:12:28'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-08-01T08:21:24.947702Z'
  name: plibMaven
  version: 8.0.29
  id: '1016464960'
  createdAt: '2024-08-01T08:21:24.947648Z'
- type: plibPypi
  modifiedAt: '2024-08-01T08:21:24.947738Z'
  name: plibPypi
  version: 1.9.9
  id: '315116326'
  createdAt: '2024-08-01T08:21:24.947729Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-31 13:11:46'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-31 13:11:46'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
